import { StyleSheet, Dimensions } from 'react-native'
import { Colors } from '../../assets/colors';
const textColor = 'rgba(0,0,0,1)';
const background = 'rgba(255,255,255,1)';
const width = Dimensions.get('screen').width;
const widthComponent = width/1.1
const home_styles = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        flex:1,
    },
    diaryBox:{
        width:widthComponent,
        elevation:3,
        shadowColor:Colors.BLACK,
        backgroundColor:Colors.WHITE,
        alignSelf:'center',
        padding:10,
        borderRadius:10,
        marginVertical:5,
        borderWidth:0.5,
        borderColor:Colors.SECONDARY,
    },
    diaryTitle:{
        color:Colors.SECONDARY,
        fontSize:18,
        fontWeight:'bold',
        width:'100%',
    },
    diaryDesc:{
        color:Colors.DARK,
        fontSize:13,
        width:'100%',
    },
    diaryTime:{
        color:Colors.DARK,
        fontSize:12,
        alignSelf:'flex-end',
    },
    emptyBox:{
        width:'100%',
        padding:10,
    },
    emptyBoxAddNew:{
        width:widthComponent,
        borderRadius:10,
        backgroundColor:Colors.WHITE,
        padding:15,
        alignSelf:'center',
        elevation:5,
        shadowColor:Colors.SECONDARY,
        flexDirection:'row',
        justifyContent:'space-evenly'
    },
    textEmpty:{
        color:Colors.SECONDARY,
    },
    iconAddnew:{
        width:50,
        height:50,
        alignSelf:'center',
    },
    headerBox:{
        width:'100%',
        padding:10,
        backgroundColor:Colors.PRIMARY,
        marginBottom:10,
    },
    flatlist:{
        height:'100%',
        width:'100%',
    },
    titleHeader:{
        alignSelf:'center',
        alignItems:'center',
        color:Colors.WHITE,
        fontSize:15,
        fontWeight:'bold',
    },
    addButton:{
        width:50,
        height:50,
        position:'absolute',
        bottom:30,
        right:30,
        zIndex:10,
    },
    addButtonImage:{
        width:'100%',
        height:'100%',
    },
    hiddenView:{
        width:widthComponent,
        height:'100%',
        alignSelf:'center',
        flexDirection:'row',
        justifyContent:'space-between',
        paddingVertical:5,
    },
    hiddenBox:{
        height:'100%',
        width:100,
        backgroundColor:Colors.RED,
        borderRadius:10,
        justifyContent:'center'
    },
    titleHiddenBox:{
        alignSelf:'center',
        color:Colors.WHITE,
    },
    iconHiddenBox:{
        width:30,
        height:30,
        alignSelf:'center',

    }

})

export default home_styles