export default {
    HOME: require('../assets/icons/list.png'),
    PROFILE: require('../assets/icons/user.png'),
    DISCOVERY: require('../assets/icons/discovery.png'),
    LOGO_TRANS: require('../assets/icons/logo_trans.png'),
    LOGO_CIRCLE: require('../assets/icons/logo_circle.png'),
    USERNAME: require('../assets/icons/username.png'),
    PASSWORD: require('../assets/icons/password.png'),
    GO: require('../assets/icons/go.png'),
    SEE: require('../assets/icons/see.png'),
    UNSEE: require('../assets/icons/unsee.png'),
    FULLNAME: require('../assets/icons/fullname.png'),
    EMAIL: require('../assets/icons/email.png'),
    INFO: require('../assets/icons/information.png'),
    CHANGEPW: require('../assets/icons/change_pw.png'),
    NEW: require('../assets/icons/new.png'),
    ADDNEW: require('../assets/icons/addnew.png'),
    DELETE: require('../assets/icons/delete.png'),
    EDIT: require('../assets/icons/edit.png'),
    SEARCHING: require('../assets/icons/search.png'),
    CLEAR: require('../assets/icons/clear.png'),
}