export default {
    ACCESS_TOKEN_FROM_STORAGE    :   'access_token_from_storage',
    REMEMBER_STATE : 'remember_state',
    USERNAME_REMEMBER : 'username',
    PASSWORD_REMEMBER : 'password',
    GO  :   'Go',
    SIGNUP: 'Sign up',
    SIGNIN: 'Sign in',
    WCBACK: 'Welcome Back!',
    CRACCOUNT:  'Create Account!',
    FULLNAME:'Full name',
    EMAIL:'Email address',
    USERNAME:'Username',
    PASSWORD:'Password',
    CPASSWORD:'Confirm password',
    REMEMBER:'Remember me',
    NOTHAVEACCOUNT : 'Not have an account? Join now!',
    HAVEACCOUNT:    'Have an account? Login now!',
}