export default {
    BASE_URL : 'https://sydiary.herokuapp.com/',
    ACCESS_TOKEN_FROM_STORAGE    :   'access_token_from_storage',
    REMEMBER_STATE : 'remember_state',
    USERNAME_STORAGE : 'username_storage',
    FULLNAME_STORAGE:   'fullname_storage',
    SAFE_SEARCH_SETTING: 'safe_search_setting',
    EMAIL_STORAGE:  'email_storage',
    USERNAME_REMEMBER : 'username',
    PASSWORD_REMEMBER : 'password',

    GO  :   'Go',
    SIGNUP: 'Sign up',
    SIGNIN: 'Sign in',
    WCBACK: 'Welcome \nBack',
    CRACCOUNT:  'Create \nAccount',
    ACCOUNTINFO: 'Account infomation',
    FULLNAME:'Full name',
    EMAIL:'Email address',
    USERNAME:'Username',
    PASSWORD:'Password',
    CPASSWORD:'Confirm password',
    REMEMBER:'Remember me',
    NOTHAVEACCOUNT : 'Not have an account? Join now!',
    HAVEACCOUNT:    'Have an account? Login now!',
    CHANGEPW:   'Password change',
    PREESSADDNEW: 'Press to add new diary',
    NODIARY:    'No diary to show',
    SYDIARY:    'Sync diary',
    NEWDIARY: 'New Diary',
    TITLE: 'Title in here',
    CONTENT: 'How was your day ?',
    SAVE:   'Save',
    CANCEL: 'Cancel',
    EDIT:   'Edit',
    DELETE: 'Delete',
    ISNEWDIARY: 'isNewDiary',
    AUTHENHEADER:'Welcome to SYDIARY',
    UPDATEPW : 'Update password',
    NEWPW: 'New password',
    CNEWPW: 'Confirm new password',
    DONE:   'Done',
    PWUPDATEDWARN:'Your password has been changed successfully.\nPlease login again with new password.',
    AGREE:'Agree',
    CONFIRMSIGNOUT:'Are you want to sign out ?',
    EDITDIARY:'Edit Diary',
    SEARCHING:'Searching',

    CATEGORIES:'Categories',
    ORIENTATIONS:'Orientations',
    VERTICAL:'Vertical',
    HORIZONTAL:'Horizontal',
    CATEGORIES      :   ['BACKGROUNDS', 'FASHION', 'NATURE', 'SIENCE', 
    'EDUCATION', 'FEELINGS', 'HEALTH', 'PEOPLE', 
    'RELIGION', 'PLACES', 'ANIMALS', 
    'INDUSTRY', 'COMPUTER', 'FOOD', 
    'SPORTS', 'TRANSPORTATION', 'TRAVEL', 
    'BUILDINGS', 'BUSINESS', 'MUSIC'],
    
}